# Generated by Django 2.1.5 on 2020-01-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191203_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='StudentSemesterProfile',
        ),
    ]
